version: "3"
services:
  app_deploy:
    container_name: app_deploy
    restart: always
    build: .
    ports:
      - "3222:3222"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
    external: true
